dubbo:
  registry:
    address: nacos://175.178.83.13:8848
  protocol:
    name: dubbo
    port: -1
  application:
    name: DemoApplication-provider
    qos-enable: true
    qos-port: 22222
    logger: slf4j
    qos-accept-foreign-ip: false
    register-mode: instance
#  metadata-report:
#    address: nacos://175.178.83.13:8848
management:
  metrics:
    enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      base-path: /
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  server:
    port: 7002
server:
  port: 8080
